# 4 Numpy

One of the most important libraries for data science with Python is [NumPy](https://numpy.org/).
If you have followed along the Jupyter Intro notebook, you should already have it installed. If, for some reason, you did not, you need to install it with pip into your virtual environment. You can do that by uncommenting the below command and executing the cell.

In [ ]:
#!pip install -U pip
#!pip install numpy==1.20.2

## Creating Vectors and Matrices with NumPy

In [5]:
import numpy as np

NumPy is a great library that enables Python users to easily work with vectors and matrices which are very important in all kinds of data science applications. It also has great [documentation](https://numpy.org/doc/) that should help you out in case you are stuck with a task.

Let us create a simple column vector with three elements, where each element has the value 7.

In [6]:
sevens_vector = np.ones(3) * 7
sevens_vector

array([7., 7., 7.])

In [7]:
sevens_vector.shape

(3,)

If we supply the function with only one value, it will create vectors. But np.ones is very flexible and can also create matrices. However, now we have to give the shape of matrix inside a tuple.

In [8]:
sevens_matrix = np.ones((4,3)) * 7
sevens_matrix

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [9]:
sevens_matrix.shape

(4, 3)

Of course you can also turn Python lists into NumPy arrays.

In [10]:
l = [[1,2,3], [4,5,6]]
x = np.array(l)
x

array([[1, 2, 3],
       [4, 5, 6]])

Accessing rows and columns works as you would expect from native Python lists.

In [11]:
x[1,1] = 1337
x

array([[   1,    2,    3],
       [   4, 1337,    6]])

## Tasks

Now, you are given a sample matrix and we want to investigate it a little. Make sure that you do not change the supplied variable names in the subtasks. Solve the tasks so that the supplied variables contain the solution.

### Matrix Manipulation

In [14]:
# sample matrix a
a = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9],
                [3, 1, 2.1, 21, 1.1, -2]])
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [18]:
# sample matrix b
b = np.array([range(6), range(10, 16)])
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

#### 4.1
The variable sol_4_1 should contain the second row of the sample matrix a.

In [16]:
sol_4_1 = a[1]
sol_4_1

array([ 1. , 22. ,  4. ,  0.1,  5.3, -9. ])

#### 4.2
The variable sol_4_2 should contain all rows except the first row of the sample matrix a.

In [22]:
sol_4_2 = a[range(1,len(a))]
sol_4_2

array([[ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

#### 4.3
The variable sol_4_3 should contain only the fifth element of every row of the sample matrix a.

In [24]:
sol_4_3 = a[range(len(a)),4]
sol_4_3

array([-2.2,  5.3,  1.1])

#### 4.4
The variable sol_4_4 should contain the third element of every row except the first row of the sample matrix a.

In [25]:
sol_4_4 = a[range(1,len(a)),2]
sol_4_4

array([4. , 2.1])

### Matrix built-in functions
Check out the docs or search the web. There are plenty of resources that will help you with the following tasks.

#### 4.5
The variable sol_4_5 should contain the absolut values of sample matrix a.

In [27]:
sol_4_5 = np.absolute(a)
sol_4_5

array([[ 2. ,  3.2,  5.5,  6.4,  2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3,  9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1,  2. ]])

#### 4.6
The variable sol_4_6 should contain the shape of sample matrix b.

In [28]:
sol_4_6 = b.shape
sol_4_6

(2, 6)

#### 4.7
The variable sol_4_7 should contain the highest value of sample matrix b.

In [31]:
sol_4_7 = b.max()
sol_4_7

15

#### 4.8
The variable sol_4_8 should contain the smallest value of sample matrix b.

In [33]:
sol_4_8 = b.min()
sol_4_8

0

#### 4.9
The variable sol_4_9 should contain the transpose of sample matrix b.

In [34]:
sol_4_9 = b.transpose()
sol_4_9

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15]])